# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.


apt addons:
cache components:
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake
    - sudo apt-get install -y libx11-xcb-dev
    - sudo apt-get install -y libssl-dev
    - sudo apt-get install -y libssh2-1-dev
    - sudo apt-get install -y libmysqlclient-dev
install:
before_script:
script:
before_cache:
after_success: # or after_failure
before_deploy:
deploy:
after_deploy:
after_script:
#---------------------------------------------------------------------------------------------------
image: gcc:6.1
language: cpp
compiler:
    - gcc

pipelines:
    default:
        - step:
            script:
                - git clone https://skynowa:5582000*aaa@bitbucket.org/skynowa/cmakelib.git $BITBUCKET_CLONE_DIR/../CMakeLib
                - git submodule sync --recursive
                - git submodule update --init --recursive
                - ./Build/makefile-yaml.sh
