# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.


sudo: required

init:
  # Print environment info ( set / systeminfo)
  - env
  - cmake --version

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake

image: gcc:6.1
language: cpp
compiler:
  - gcc


pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - sudo apt-get install -y cmake
          - ./Build/makefile.sh

deps:
  apt_get:
  - name: cmake


addons:
  apt:
    packages:
    - cmake
    - time
