#--------------------------------------------------------------------------------------------------
# \file  Config.cmake
# \brief Config for xLib
#--------------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------------
# options
get_directory_property(IS_PARENT_SCOPE PARENT_DIRECTORY)

if (IS_PARENT_SCOPE)
    set(cmOPTION_PROJECT_LIB_STATIC    1 PARENT_SCOPE)
    set(cmOPTION_PROJECT_LIB_SHARE     0 PARENT_SCOPE)
    set(cmOPTION_PROJECT_LIB_MODULE    0 PARENT_SCOPE)
    set(cmOPTION_BUILD_TESTS           1 PARENT_SCOPE)

    set(CMAKE_CONFIGURATION_TYPES      "Debug;Release;RelWithDebInfo" STRING "" PARENT_SCOPE)
    set(CMAKE_BUILD_TYPE               "RelWithDebInfo" PARENT_SCOPE)

    set(OPTION_CPP_98                  0 PARENT_SCOPE)
    set(OPTION_CPP_11                  1 PARENT_SCOPE)
    set(OPTION_CPP_14                  0 PARENT_SCOPE)
    set(OPTION_CPP_17                  0 PARENT_SCOPE)
    set(OPTION_UNICODE                 0 PARENT_SCOPE)
    set(cmOPTION_DEBUG_MODE_MSGBOX     0 PARENT_SCOPE)
    set(cmOPTION_DEBUG_MODE_STDOUT     1 PARENT_SCOPE)
    set(cmOPTION_DEBUG_MODE_LOG        0 PARENT_SCOPE)
    set(cmOPTION_DEBUG_MODE_STDOUT_LOG 0 PARENT_SCOPE)
    set(cmOPTION_DEBUG_MODE_EXCEPTION  0 PARENT_SCOPE)
    set(cmOPTION_DEBUG_MODE_NO         0 PARENT_SCOPE)
    set(cmOPTION_BUILD_MSG             0 PARENT_SCOPE)
    set(cmOPTION_TEST_PRIVATE          0 PARENT_SCOPE)
    set(cmOPTION_TEST_TRACING          1 PARENT_SCOPE)
else()
    set(cmOPTION_PROJECT_LIB_STATIC    1)
    set(cmOPTION_PROJECT_LIB_SHARE     0)
    set(cmOPTION_PROJECT_LIB_MODULE    0)
    set(cmOPTION_BUILD_TESTS           1)

    set(CMAKE_CONFIGURATION_TYPES      "Debug;Release;RelWithDebInfo" STRING "")
    set(CMAKE_BUILD_TYPE               "RelWithDebInfo")
        # None           (CMAKE_C_FLAGS or CMAKE_CXX_FLAGS used)
        # Debug          (CMAKE_C_FLAGS_DEBUG or CMAKE_CXX_FLAGS_DEBUG)
        # Release        (CMAKE_C_FLAGS_RELEASE or CMAKE_CXX_FLAGS_RELEASE)
        # RelWithDebInfo (CMAKE_C_FLAGS_RELWITHDEBINFO or CMAKE_CXX_FLAGS_RELWITHDEBINFO
        # MinSizeRel     (CMAKE_C_FLAGS_MINSIZEREL or CMAKE_CXX_FLAGS_MINSIZEREL)

    set(OPTION_CPP_98                  0)
    set(OPTION_CPP_11                  1)
    set(OPTION_CPP_14                  0)
    set(OPTION_CPP_17                  0)
    set(OPTION_UNICODE                 0)
    set(cmOPTION_DEBUG_MODE_MSGBOX     0)
    set(cmOPTION_DEBUG_MODE_STDOUT     1)
    set(cmOPTION_DEBUG_MODE_LOG        0)
    set(cmOPTION_DEBUG_MODE_STDOUT_LOG 0)
    set(cmOPTION_DEBUG_MODE_EXCEPTION  0)
    set(cmOPTION_DEBUG_MODE_NO         0)
    set(cmOPTION_BUILD_MSG             0)
    set(cmOPTION_TEST_PRIVATE          0)
    set(cmOPTION_TEST_TRACING          1)
endif()

message("")
message("CMake")
message(STATUS "CMAKE_VERSION                  : ${CMAKE_VERSION}")
message(STATUS "CMAKE_GENERATOR                : ${CMAKE_GENERATOR}")
message(STATUS "Complier                       : ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "CMAKE_CONFIGURATION_TYPES      : ${CMAKE_CONFIGURATION_TYPES}")
message(STATUS "CMAKE_BUILD_TYPE               : ${CMAKE_BUILD_TYPE}")
message("")
message("Options")
message(STATUS "cmOPTION_PROJECT_LIB_STATIC    : ${cmOPTION_PROJECT_LIB_STATIC}")
message(STATUS "cmOPTION_PROJECT_LIB_SHARE     : ${cmOPTION_PROJECT_LIB_SHARE}")
message(STATUS "cmOPTION_PROJECT_LIB_MODULE    : ${cmOPTION_PROJECT_LIB_MODULE}")
message(STATUS "cmOPTION_BUILD_TESTS           : ${cmOPTION_BUILD_TESTS}")
message("")
message(STATUS "OPTION_CPP_98                  : ${OPTION_CPP_98}")
message(STATUS "OPTION_CPP_11                  : ${OPTION_CPP_11}")
message(STATUS "OPTION_CPP_14                  : ${OPTION_CPP_14}")
message(STATUS "OPTION_CPP_17                  : ${OPTION_CPP_17}")
message(STATUS "OPTION_UNICODE                 : ${OPTION_UNICODE}")
message(STATUS "cmOPTION_DEBUG_MODE_MSGBOX     : ${cmOPTION_DEBUG_MODE_MSGBOX}")
message(STATUS "cmOPTION_DEBUG_MODE_STDOUT     : ${cmOPTION_DEBUG_MODE_STDOUT}")
message(STATUS "cmOPTION_DEBUG_MODE_LOG        : ${cmOPTION_DEBUG_MODE_LOG}")
message(STATUS "cmOPTION_DEBUG_MODE_STDOUT_LOG : ${cmOPTION_DEBUG_MODE_STDOUT_LOG}")
message(STATUS "cmOPTION_DEBUG_MODE_EXCEPTION  : ${cmOPTION_DEBUG_MODE_EXCEPTION}")
message(STATUS "cmOPTION_DEBUG_MODE_NO         : ${cmOPTION_DEBUG_MODE_NO}")
message(STATUS "cmOPTION_BUILD_MSG             : ${cmOPTION_BUILD_MSG}")
message(STATUS "cmOPTION_TEST_PRIVATE          : ${cmOPTION_TEST_PRIVATE}")
message(STATUS "cmOPTION_TEST_TRACING          : ${cmOPTION_TEST_TRACING}")
message("")
#--------------------------------------------------------------------------------------------------
