/**
 * \file  Random.cpp
 * \brief random generator
 */


#include "Random.h"

#include <xLib/Core/Functions.h>
#include <xLib/Core/Utils.h>
#include <xLib/Core/Format.h>
#include <xLib/Test/Test.h>
#include <xLib/Debug/Debug.h>
#include <xLib/Debug/NativeError.h>
#include <xLib/Debug/ErrorReport.h>
#include <xLib/Debug/Debugger.h>
#include <xLib/Debug/StackTrace.h>

#if   xENV_WIN
    #include "Platform/Win/Random_win.inl"
#elif xENV_UNIX
    #include "Platform/Unix/Random_unix.inl"
#endif

#if xENV_WIN
    #include <xLib/Core/Platform/Win/Functions_win.inl>
#endif


namespace xl::crypt
{

/**************************************************************************************************
*    ISeedPolicy
*
**************************************************************************************************/

//-------------------------------------------------------------------------------------------------
ISeedPolicy::ISeedPolicy()
{
    _seed = _seedTimeBased();
}
//-------------------------------------------------------------------------------------------------
uint_t
ISeedPolicy::_seedTimeBased() const
{
    timeval tv {};
    int_t iRv = /*::*/gettimeofday(&tv, nullptr);
    xTEST_DIFF(iRv, - 1);

    return static_cast<uint_t>( tv.tv_usec );
}
//-------------------------------------------------------------------------------------------------
/* static */
long_t
ISeedPolicy::valueMax()
{
   /**
    * FAQ: RAND_MAX
    *
    * Maximum possible value generated by std::rand (int)
    * This value is library-dependent, but is guaranteed to be at least 32767 on any standard
    * library implementation
    */

    return static_cast<int>( RAND_MAX );
}
//-------------------------------------------------------------------------------------------------


/**************************************************************************************************
*    StdSeedPolicy
*
**************************************************************************************************/

//-------------------------------------------------------------------------------------------------
StdSeedPolicy::StdSeedPolicy()
{
    _ctor_impl();
}
//-------------------------------------------------------------------------------------------------
/* virtual */
long_t
StdSeedPolicy::next()
{
    return _next_impl();
}
//-------------------------------------------------------------------------------------------------


/**************************************************************************************************
*    NativeSeedPolicy
*
**************************************************************************************************/

//-------------------------------------------------------------------------------------------------
NativeSeedPolicy::NativeSeedPolicy()
{
    _ctor_impl();
}
//-------------------------------------------------------------------------------------------------
/* virtual */
NativeSeedPolicy::~NativeSeedPolicy()
{
    _dtor_impl();
}
//-------------------------------------------------------------------------------------------------
/* virtual */
long_t
NativeSeedPolicy::next()
{
    return _next_impl();
}
//-------------------------------------------------------------------------------------------------

} // namespace
