#--------------------------------------------------------------------------------------------------
# \file  main.yml
# \brief
#--------------------------------------------------------------------------------------------------


name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    # runs-on: windows-2019

    steps:
      # - name: Upgrade
        # run: sudo apt update && sudo apt upgrade

      - uses: actions/checkout@v2

      - name: Install - Libs
        run: cd ./Tools && ./install_libs.sh

      # - name: Install - Static Analysis
        # run: cd ./Tools && ./install_cppcheck.sh && ./install_clang_tidy.sh && ./install_pvs_studio.sh

      - name: Checkout - CMakeLib
        uses: actions/checkout@v2
        with:
          repository: skynowa/CMakeLib
          path: CMakeLib

      - name: Install - CMakeLib
        run: cd ./CMakeLib && ./install.sh

      - name: Configure - xLib
        run: cd ./Build && ./eclipse.sh

      - name: Build - xLib
        run: cd ./Build && ./build.sh
