#--------------------------------------------------------------------------------------------------
# \file  main.yml
# \brief
#
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
#--------------------------------------------------------------------------------------------------


name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC (C++17)",
            os: windows-latest,
            build_type: "Debug",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            generators: "Visual Studio 16 2019"
          }
        - {
            name: "Ubuntu Latest GCC (C++17)",
            os: ubuntu-latest,
            build_type: "Debug",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{github.token}}

      - name: xLib - Vheckout
        uses: actions/checkout@v2
        with:
          repository: skynowa/xLib
          path: ${{github.workspace}}/xLib

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      # xLib-data
      - name: xLib-data - Vheckout
        uses: actions/checkout@v2
        with:
          repository: skynowa/xLib-data
          path: ${{github.workspace}}/xLib-data

      - name: xLib-data - Install
        run: cd ${{github.workspace}}/xLib-data/Libs/ubuntu-20.04 && ./install.sh

      # Libs
      - name: Libs - Install
        run: cd ${{github.workspace}}/xLib/Tools && ./install_libs.sh

      # Static Analysis
      ## - name: Static Analysis - Install
      ##   run: |
      ##     cd ${{github.workspace}}/xLib/Tools/StaticAnalisis &&
      ##     ./install_cppcheck.sh   &&
      ##     ./install_clang_tidy.sh &&
      ##     ./install_pvs_studio.sh &&
      ##     ./install_configs.sh ${{github.workspace}}/xLib-data/Configs/StaticAnalisis

      # CMakeLib
      - name: CMakeLib - checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/CMakeLib
          path: ${{github.workspace}}/CMakeLib

      - name: CMakeLib - Install
        run: cd ${{github.workspace}}/CMakeLib && ./install.sh

        # xLib
      - name: xLib - Configure
        run: cd ${{github.workspace}}/xLib/Build && ./eclipse.sh

      - name: Info
      #  run: ./SystemInfoEx.sh && ./DevInfo.sh && env && exit 1
        run: echo "github.workspace - ${{github.workspace}}" && ls -la

      - name: xLib - Build
        run: cd ${{github.workspace}}/xLib/Build && ./build.sh

      # - name: xLib - Unit Tests (optional)
      #   run: ./unit_tests.sh IpcSemaphore

      - name: xLib - Tests
        run: cd ${{github.workspace}}/xLib/Build && ./tests.sh

      # Static Analysis
      ## - name: Static Analysis - run
      ##   run: |
      ##     cd ${{github.workspace}}/xLib/Tools/StaticAnalisis &&
      ##     ./run_cppcheck.sh   &&
      ##     ./run_clang_tidy.sh &&
      ##     ./run_pvs_studio.sh || 0

  # build_windows:
  #   runs-on: windows-2019
