#--------------------------------------------------------------------------------------------------
# \file  main.yml
# \brief
#--------------------------------------------------------------------------------------------------


name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    # runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: <Libs> Install
        run: cd ./Tools && ./install_libs.sh
      # - name: Install - Static Analysis
        # run: cd ./Tools && ./install_cppcheck.sh && ./install_clang_tidy.sh && ./install_pvs_studio.sh

      - name: CMakeLib-Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/CMakeLib
          path: CMakeLib

      - name: CMakeLib-Install
        run: cd ./CMakeLib && ./install.sh

      - name: xLib-Configure
        run: cd ./Build && ./makefile.sh

      - name: xLib-Build
        run: cd ./Build && ./build.sh
