#--------------------------------------------------------------------------------------------------
# \file  main.yml
# \brief
#
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
#--------------------------------------------------------------------------------------------------


name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        # - {
        #     name: "ubuntu-20.04",
        #     os: ubuntu-20.04,
        #     build_type: "Debug",
        #     cc: "gcc",
        #     cxx: "g++"
        #   }
        - {
            name: "Ubuntu Latest GCC (C++17)",
            os: ubuntu-latest,
            build_type: "Debug",
            compiler: "g++",
            generators: "Ninja"
          }
        - {
            name: "ubuntu-20.04-clang-10",
            os: ubuntu-20.04-clang-10,
            build_type: "Debug",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja"
          }
        - {
            name: "Windows Latest MSVC (C++17)",
            os: windows-latest,
            build_type: "Debug",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            generators: "Visual Studio 16 2019"
          }

    steps:
      ##############################################################################################
      # Cancel
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{github.token}}

      ##############################################################################################
      # Trace
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      ##############################################################################################
      # Compilers
      # - name: Install dependencies on ubuntu - Clang
      #   if: startsWith(matrix.config.cxx, 'clang++')
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install \
      #       clang++-10 \
      #       clang-tidy-10 \
      #       clang-tools-10

      ##############################################################################################
      # xLib-data
      - name: xLib-data - Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/xLib-data
          path: ${{github.workspace}}/xLib-data

      ##############################################################################################
      # Static Analysis
      ## - name: Static Analysis - Install
      ##   run: |
      ##     cd ${{github.workspace}}/xLib/Tools/StaticAnalisis &&
      ##     ./install_cppcheck.sh   &&
      ##     ./install_clang_tidy.sh &&
      ##     ./install_pvs_studio.sh &&
      ##     ./install_configs.sh ${{github.workspace}}/xLib-data/Configs/StaticAnalisis

      ##############################################################################################
      # CMakeLib
      - name: CMakeLib - Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/CMakeLib
          path: ${{github.workspace}}/CMakeLib

      - name: CMakeLib - Install
        run: cd ${{github.workspace}}/CMakeLib && ./install.sh

      ##############################################################################################
      # xLib
      # Checkout
      - name: xLib - Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/xLib
          path: ${{github.workspace}}/xLib

      # Libs
      - name: Libs - Install
        run: cd ${{github.workspace}}/xLib/Tools && ./install_libs.sh

      - name: xLib - Configure
        run: cd ${{github.workspace}}/xLib/Build && ./eclipse.sh

      - name: xLib - Trace
        # run: ./SystemInfoEx.sh && ./DevInfo.sh && env && exit 1
        run: echo "github.workspace - ${{github.workspace}}" && ls -la

      - name: xLib - Build
        run: cd ${{github.workspace}}/xLib/Build && ./build.sh
        shell: bash
        env:
          CC:  clang
          CXX: clang++

      # - name: xLib - Unit Tests (optional)
      #   run: ./unit_tests.sh IpcSemaphore

      - name: xLib - Tests
        run: cd ${{github.workspace}}/xLib/Build && ./tests.sh

      ##############################################################################################
      # Static Analysis
      ## - name: Static Analysis - run
      ##   run: |
      ##     cd ${{github.workspace}}/xLib/Tools/StaticAnalisis &&
      ##     ./run_cppcheck.sh   &&
      ##     ./run_clang_tidy.sh &&
      ##     ./run_pvs_studio.sh || 0
