#--------------------------------------------------------------------------------------------------
# \file  main.yml
# \brief
#
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
#--------------------------------------------------------------------------------------------------


name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        # - {
        #     name: "Ubuntu-20.04 (GCC)",
        #     os: ubuntu-20.04,
        #     build_type: "Debug",
        #     compiler: "g++",
        #     cc: "gcc",
        #     cxx: "g++"
        #   }
        # - {
        #     name: "Ubuntu-20.04 (Clang)",
        #     os: ubuntu-20.04,
        #     build_type: "Debug",
        #     compiler: "clang++",
        #     cc: "clang",
        #     cxx: "clang++"
        #   }
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            build_type: "Debug",
            compiler: "cl",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
          }
        # - {
        #     name: "macOS Latest Clang",
        #     os: macos-latest,
        #     build_type: "Debug",
        #     compiler: "clang++",
        #     cc: "clang",
        #     cxx: "clang++"
        #   }

    steps:
      ##############################################################################################
      # Cancel
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{github.token}}

      ##############################################################################################
      # Trace
      # - name: Print env
      #   run: |
      #     echo github.event.action: ${{ github.event.action }}
      #     echo github.event_name:   ${{ github.event_name }}

      ##############################################################################################
      # xLib-data
      - name: xLib-data - Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/xLib-data
          path: ${{github.workspace}}/xLib-data

      ##############################################################################################
      # Static Analysis
      ## - name: Static Analysis - Install
      ##   run: |
      ##     cd ${{github.workspace}}/xLib/Tools/StaticAnalisis &&
      ##     ./install_cppcheck.sh   &&
      ##     ./install_clang_tidy.sh &&
      ##     ./install_pvs_studio.sh &&
      ##     ./install_configs.sh ${{github.workspace}}/xLib-data/Configs/StaticAnalisis

      ##############################################################################################
      # CMakeLib
      - name: CMakeLib - Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/CMakeLib
          path: ${{github.workspace}}/CMakeLib

      - name: CMakeLib - Install
        run: cd ${{github.workspace}}/CMakeLib && ./install.sh

      ##############################################################################################
      # xLib
      # Checkout
      - name: xLib - Checkout
        uses: actions/checkout@v2
        with:
          repository: skynowa/xLib
          path: ${{github.workspace}}/xLib

      # Env
      # - name: Compiler Env
      #   run: |
      #     echo "CXX=${{ matrix.config.compiler }}" >> $GITHUB_ENV
      #   shell: bash

      - name: Conan install
        run: |
          pip install conan

      # Libs
      - name: Libs - Install
        run: cd ${{github.workspace}}/xLib/Tools && ./install_libs.sh

      - name: Libs - Install (Win)
        run: conan install OpenSSL/1.1.1l@conan/stable

      - name: xLib - Configure
        run: cd ${{github.workspace}}/xLib/Build && ./eclipse.sh

      - name: xLib - Trace
        # run: ./SystemInfoEx.sh && ./DevInfo.sh && env && exit 1
        run: echo "github.workspace - ${{github.workspace}}" && ls # -la

      - name: xLib - Build
        run: cd ${{github.workspace}}/xLib/Build && ./build.sh

      # - name: xLib - Unit Tests (optional)
      #   run: ${{github.workspace}}/xLib_eclipse/Tests/System/Test_ProcessInfo

      - name: xLib - Tests
        run: cd ${{github.workspace}}/xLib/Build && ./tests.sh

      ##############################################################################################
      # Static Analysis
      ## - name: Static Analysis - run
      ##   run: |
      ##     cd ${{github.workspace}}/xLib/Tools/StaticAnalisis &&
      ##     ./run_cppcheck.sh   &&
      ##     ./run_clang_tidy.sh &&
      ##     ./run_pvs_studio.sh || 0
